# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='registration_users',
        ),
    ]
